name       : subsurface
version    : 4.8.4
release    : 1
source     :
    - https://subsurface-divelog.org/downloads/Subsurface-4.8.4.tgz : 3e806442e602da188666e3905c2b66232e2b99f4bf4ff4bd42002ee1585ef3eb
license    : GPL-2.0-or-later
component  : office
summary    : An open source divelog program for recreational, tech, and free-divers
description: |
    Subsurface is an open source divelog program for recreational, tech, and free-divers.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(libzip)
    - pkgconfig(Qt5Bluetooth)
    - pkgconfig(Qt5Location)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(sqlite3)
    - grantlee-devel
    - subsurface-libdc-devel
setup      : |
    %cmake -B build \
           -DLIBDIVECOMPUTER_INCLUDE_DIR=/usr/include/libdivecomputer .
build      : |
    %make -C build
install    : |
    %make_install -C build
    rm $installdir/usr/bin/subsurface.debug
